name: Java CI
run-name: Java CI on ${{ github.ref}} by ${{ github.actor }}
on: [push]
jobs:
  Maven-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots package
#        run: mvn -B package --file pom.xml
        run: mvn --batch-mode --update-snapshots package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
