name: Java CI
run-name: Java CI on ${{ github.ref}} by ${{ github.actor }}
on:
  workflow_dispatch:
  push:
jobs:
  Maven-Build:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Build with Maven
        #        run: mvn -B package --file pom.xml
        run: mvn --batch-mode --update-snapshots verify --file pom.xml
      - name: Copy artifact
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 5 # Default 90 (days)
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@967a81f8b657c87f7c3e96b62301cb1a48efef29
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
